### ISSUE TITLE
Autorization failure, but I type the correct password

### ISSUE THREAD

**Issue by ooker777** [neo4j-contrib/neovis.js#207]
I'm pretty sure my username and password is correct, since I can use them to login via http://localhost:7474. My script is:
```js
function draw() {
			var config = {
                containerId: "viz",
                neo4j: { // this can also be a Neo4J driver instance now instead of object
                    serverUrl: 'bolt://localhost:7687',
                    serverUser: 'neo4j',
                    serverPassword: 'a',
                    driverConfig: { // full driver config object by neo4j https://neo4j.com/docs/api/javascript-driver/current/function/index.html#configuration
                        encrypted: "ENCRYPTION_ON",
                        trust: "TRUST_SYSTEM_CA_SIGNED_CERTIFICATES"
                    }
                },
...
```
(Here is the [full script](https://gist.github.com/ooker777/06029ac7efb815eb14e7e3f79f7782e7 "test.html"))
 
Here is the console:
```
Neo4jError: The client is unauthorized due to authentication failure.

    at d:\GitHub\neovis.js\node_modules\neo4j-driver\lib\result.js:277:15
    at new t (d:\GitHub\neovis.js\node_modules\neo4j-driver\lib\result.js:68:19)
    at t.value (d:\GitHub\neovis.js\node_modules\neo4j-driver\lib\session.js:174:14)
    at t.value (d:\GitHub\neovis.js\node_modules\neo4j-driver\lib\session.js:135:19)
    at t.value (d:\GitHub\neovis.js\src\neovis.js:309:5)
    at draw (d:\GitHub\neovis.js\test.html:84:8)
    at onload (file:///D:/GitHub/neovis.js/test.html:90:23) {code: 'Neo.ClientError.Security.Unauthorized', name: 'Neo4jError', stack: 'Neo4jError: The client is unauthorized due to…(file:///D:/GitHub/neovis.js/test.html:90:23)', message: 'The client is unauthorized due to authentication failure.'}
arg0:Neo4jError: The client is unauthorized due to authentication failure.

    at file:///D:/GitHub/neovis.js/dist/neovis.js:16:115774
    at new t (file:///D:/GitHub/neovis.js/dist/neovis.js:16:115854)
    at t.value (file:///D:/GitHub/neovis.js/dist/neovis.js:16:85553)
    at t.value (file:///D:/GitHub/neovis.js/dist/neovis.js:16:84750)
    at t.value (file:///D:/GitHub/neovis.js/dist/neovis.js:76:28693)
    at draw (file:///D:/GitHub/neovis.js/test.html:84:8)
    at onload (file:///D:/GitHub/neovis.js/test.html:90:23) {code: 'Neo.ClientError.Security.Unauthorized', name: 'Neo4jError', stack: 'Neo4jError: The client is unauthorized due to…(file:///D:/GitHub/neovis.js/test.html:90:23)', message: 'The client is unauthorized due to authentication failure.'}
code:'Neo.ClientError.Security.Unauthorized'
message:'The client is unauthorized due to authentication failure.'
name:'Neo4jError'
stack:'Neo4jError: The client is unauthorized due to authentication failure.\n\n    at file:///D:/GitHub/neovis.js/dist/neovis.js:16:115774\n    at new t (file:///D:/GitHub/neovis.js/dist/neovis.js:16:115854)\n    at t.value (file:///D:/GitHub/neovis.js/dist/neovis.js:16:85553)\n    at t.value (file:///D:/GitHub/neovis.js/dist/neovis.js:16:84750)\n    at t.value (file:///D:/GitHub/neovis.js/dist/neovis.js:76:28693)\n    at draw (file:///D:/GitHub/neovis.js/test.html:84:8)\n    at onload (file:///D:/GitHub/neovis.js/test.html:90:23)'
[[Prototype]]:e
value @ d:\GitHub\neovis.js\src\neovis.js:56:12
```

**Comment by thebestnom** [comment]
I would have looked at the network tab to see the status there 😅  I don't have enough data to help you here I know it works for me on my pc without certificate and on hosted neo4j sandbox as much as I tested

**Comment by thebestnom** [comment]
There is messages there

**Comment by thebestnom** [comment]
It's just weird to me to run locally with ssl on 😅

**Comment by ooker777** [comment]
wait, I comment out the driverConfig section and it runs now 😂. Thank you so much for your patience. I know this is a silly problem that's not worth your time 😣

**Comment by thebestnom** [comment]
No problem 😄 glad I helped
