### ISSUE TITLE
Cannot use NEOVIS_ADVANCED_CONFIG

### ISSUE THREAD

**Issue by leema2345** [neo4j-contrib/neovis.js#358]
Hi. I'm trying to use NEOVIS_ADVANCED_CONFIG and have searched all over this forum to try and decipher how to use it

I first got neovis by doing 
`    <script type="text/javascript" src="https://cdn.neo4jlabs.com/neovis.js/v1.2.1/neovis.js"></script>
`
This allows me to connect to the database and outputs the graph......But i want to choose my relationship colors, so i realised i need a newer version with NEOVIS_ADVANCED_CONFIG

I cloned the latest version repo and wrote this script 

`<script type="text/javascript" src="./static/js/neovis.js/dist/neovis.js"></script>`

followed by 

`<script type="module">
        import NeoVis, {NEOVIS_ADVANCED_CONFIG} from "./static/js/neovis.js/dist/neovis.js";
</script> 
    `
but now i'm getting two errors  ...................

> Uncaught` SyntaxError: The requested module './static/js/neovis.js/dist/neovis.js' does not provide an export named 'NEOVIS_ADVANCED_CONFIG' (at (index):59:21)

and when i try to draw the graph, i get

> neovis.ts:294  Neo4jError: The client is unauthorized due to authentication failure.

    at new t (result.js:239:17)
    at t._run (session.js:174:16)
    at t.run (session.js:139:21)
    at RB.YB (neovis.ts:596:11)
    at RB.render (neovis.ts:568:8)
    at draw ((index):93:13)
    at HTMLButtonElement.onclick ((index):163:203)

In MY draw() function I have the correct password and username, so i'm unsure why i'm getting an authentication error.
ANY idea how to get around these?

**Comment by thebestnom** [comment]
For the second error you are probably trying to connect http from https or the other way around, the third error is probably you run your draw before the neovis downloaded
Anyway best way to use the package is of course using npm
As for the first I didn't create a module js, you have to use webpack or other of that kind to import it es6 style

**Comment by sysu17363055** [comment]
hello, have you solved this problem?

**Comment by FStriewski** [comment]
For the first problem, check the example from this repo for how it is done:
https://github.com/neo4j-contrib/neovis.js/blob/master/examples/advanced-example.html

**Comment by sysu17363055** [comment]
您好，我是刘琼雯。您的邮件我已经收到，会尽快回复，祝一切安好~
