### ISSUE TITLE
fail to connect to Neo4j AuraDB

### ISSUE THREAD

**Issue by Liuz233** [neo4j-contrib/neovis.js#388]
Here is my config in HTML
When I try to load the draw the graph from Neo4j AuraDB, it failed and show nothing

console in web browser shows
![image](https://github.com/user-attachments/assets/d0d7194f-c77f-4abb-a71a-30931d172570)
But I have write my Neo4j AuraDB url, username, password in config. Why it still try to connect to localhost:7687?

How can I fix it?
```

    <!-- FIXME: load from dist -->
    <script type="text/javascript" src="../static/neovis.js"></script>


    <script
            src="https://code.jquery.com/jquery-3.2.1.min.js"
            integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
            crossorigin="anonymous"></script>

    <script type="text/javascript">
		// define config car
		// instantiate nodevis object
		// draw

		var viz;

		function draw() {
			var config = {
				containerId: "viz",
				neo4j: {
				server_url: "bolt://xx.xx.xx.xx:7687",
				server_user: "neo4j",
				server_password: "navigators-bowl-flake",
				},
				labels: {
					Character: {
						label: "name",
						value: "pagerank",
						group: "community"
					}
				},
				relationships: {
					INTERACTS: {
						value: "weight"
					}
				},
				initialCypher: "MATCH p=()-->() RETURN p"
			};

			viz = new NeoVis.default(config);
			viz.render();
			console.log(viz);

		}
    </script>
</head>
<body onload="draw()">
<div id="viz"></div>
```

**Comment by prsfreal** [comment]
your server_URL is using bolt - looking for a local instance. You want to connect to AuraDB - which should look something like this:

'neo4j+s://7e1dfa.databases.neo4j.io:7687'

This can be found in the Aura_db console.

Also be aware that if you are using the feee instance you may come across a bug where all nodes return but only one relationship. https://github.com/neo4j-contrib/neovis.js/issues/367

Switching to paid instance or local install fixes issue.

**Comment by Liuz233** [comment]
> your server_URL is using bolt - looking for a local instance. You want to connect to AuraDB - which should look something like this:
> 
> 'neo4j+s://7e1dfa.databases.neo4j.io:7687'
> 
> This can be found in the Aura_db console.
> 
> Also be aware that if you are using the feee instance you may come across a bug where all nodes return but only one relationship. #367
> 
> Switching to paid instance or local install fixes issue.

Thank you. I try to build my local neo4j and face no bug.

**Comment by adoresever** [comment]
**Help!** I encountered using neo4j aura to link neo4j+s://85945aee.databases.neo4j.io, but authentication problems occurred after trying for a long time.
![image](https://github.com/user-attachments/assets/47c5ac93-398b-4400-9a46-2d48cab0b897)

**Comment by spyroskotsakis** [comment]
Hello,
I'm running one of the examples on localhost with Neo4j using AuraDB and ran into an issue.

I'm seeing the following error, and below is an example of the connection configuration (I've modified the details, so they're not the actual ones).

'serverUrl': 'neo4j+s://AU4dUbid.databases.neo4j.io',
 'serverUser': 'neo4j',
 'serverPassword': 'UcOBWs7W2ZGdY2G6ziey'

Any idea what might be causing this and how I can fix it?
Thanks!

error:
index.js:462 Uncaught Error: Encryption/trust can only be configured either through URL or config, not both
    at RB.MB (neovis.ts:366:64)
    at new RB (neovis.ts:285:7)
    at draw (advanced-test.html:81:10)
    at onload (advanced-test.html:88:23)

**Comment by oldwangmate** [comment]
@spyroskotsakis Hi, have you solved this problem? I have the same problem, can you tell me how you solved it?
Thanks!

**Comment by DreamingJ** [comment]
use bolt:
